In [11]:
import pandas as pd
# read csv
weather = pd.read_csv("../Input/open_meteo.csv")
# dimension check
print("weather dimension:", weather.shape)
# inspecting columns and nulls
print("\nweather columns:")
print(weather.info())
print("\nweather null counts:")
print(weather.isnull().sum())
weather.head(10)

weather dimension: (689588, 8)

weather columns:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689588 entries, 0 to 689587
Data columns (total 8 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   time                           689588 non-null  object
 1   weather_code (wmo code)        689588 non-null  int64
 2   temperature_2m_mean (°F)       689588 non-null  float64
 3   cloud_cover_mean (%)           689588 non-null  int64
 4   wind_speed_10m_mean (mp/h)     689588 non-null  float64
 5   relative_humidity_2m_mean (%)  689588 non-null  int64
 6   precipitation_sum (inch)       689588 non-null  float64
 7   IATA_CODE                      689588 non-null  object
dtypes: float64(3), int64(3), object(2)
memory usage: 42.1+ MB
None

weather null counts:
time                             0
weather_code (wmo code)          0
temperature_2m_mean (°F)         0
cloud_cover_mean (%)             0
wind_speed_10m_mean (mp/h)       0
relative_humidity_2m_mean (%)    0
precipitation_sum (inch)         0
IATA_CODE                        0
dtype: int64

,time,weather_code (wmo code),temperature_2m_mean (°F),cloud_cover_mean (%),wind_speed_10m_mean (mp/h),relative_humidity_2m_mean (%),precipitation_sum (inch),IATA_CODE
0,2019-01-01,63,60.0,93,5.1,93,0.378,ATL
1,2019-01-02,63,53.0,85,4.3,93,0.571,ATL
2,2019-01-03,61,53.1,100,4.6,93,0.386,ATL
3,2019-01-04,65,53.5,85,13.1,83,1.315,ATL
4,2019-01-05,3,47.9,28,11.6,66,0.000,ATL
5,2019-01-06,3,52.0,16,5.4,71,0.000,ATL
6,2019-01-07,3,52.6,74,6.8,77,0.000,ATL
7,2019-01-08,51,56.1,76,10.8,80,0.016,ATL
8,2019-01-09,1,43.6,3,14.5,45,0.000,ATL
9,2019-01-10,3,34.2,34,12.1,54,0.000,ATL

In [12]:
num_unique_iata = weather["IATA_CODE"].nunique()
print(f"Unique IATA codes: {num_unique_iata}")

Unique IATA codes: 380

In [13]:
weather["airport_time"] = (
    weather["IATA_CODE"] + "_" + weather["time"].astype(str)
)
weather.head(10)

,time,weather_code (wmo code),temperature_2m_mean (°F),cloud_cover_mean (%),wind_speed_10m_mean (mp/h),relative_humidity_2m_mean (%),precipitation_sum (inch),IATA_CODE,airport_time
0,2019-01-01,63,60.0,93,5.1,93,0.378,ATL,ATL_2019-01-01
1,2019-01-02,63,53.0,85,4.3,93,0.571,ATL,ATL_2019-01-02
2,2019-01-03,61,53.1,100,4.6,93,0.386,ATL,ATL_2019-01-03
3,2019-01-04,65,53.5,85,13.1,83,1.315,ATL,ATL_2019-01-04
4,2019-01-05,3,47.9,28,11.6,66,0.000,ATL,ATL_2019-01-05
5,2019-01-06,3,52.0,16,5.4,71,0.000,ATL,ATL_2019-01-06
6,2019-01-07,3,52.6,74,6.8,77,0.000,ATL,ATL_2019-01-07
7,2019-01-08,51,56.1,76,10.8,80,0.016,ATL,ATL_2019-01-08
8,2019-01-09,1,43.6,3,14.5,45,0.000,ATL,ATL_2019-01-09
9,2019-01-10,3,34.2,34,12.1,54,0.000,ATL,ATL_2019-01-10

In [14]:
weather = weather.drop(columns=["IATA_CODE"])
weather = weather.rename(columns={
    "weather_code (wmo code)": "weather_code",
    "temperature_2m_mean (°F)": "temperature_2m_mean",
    "cloud_cover_mean (%)": "cloud_cover_mean",
    "wind_speed_10m_mean (mp/h)": "wind_speed_10m_mean",
    "relative_humidity_2m_mean (%)": "relative_humidity_2m_mean",
    "precipitation_sum (inch)": "precipitation_sum"
})


weather.to_csv(
    "../Output/manny_weather_cleaned.csv",
    index=False
)

print(weather.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689588 entries, 0 to 689587
Data columns (total 8 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   time                       689588 non-null  object
 1   weather_code               689588 non-null  int64
 2   temperature_2m_mean        689588 non-null  float64
 3   cloud_cover_mean           689588 non-null  int64
 4   wind_speed_10m_mean        689588 non-null  float64
 5   relative_humidity_2m_mean  689588 non-null  int64
 6   precipitation_sum          689588 non-null  float64
 7   airport_time               689588 non-null  object
dtypes: float64(3), int64(3), object(2)
memory usage: 42.1+ MB
None